parameters:
  - name: applyDeployment
  - name: azureMsiCredFile
  - name: backendContainerName
  - name: backendResourceGroupName
  - name: backendStorageAccountName
  - name: releaseId
  - name: stage
  - name: workingDirectory

jobs:
  - job: provisionEnvironment
    displayName: "Provision environment"

    variables:
      - name: tfplanName
        value: tfplan-${{ parameters.releaseId }}.tfplan
    
    steps:
      - template: ../steps/backend-setup.yml
        parameters:
          azureMsiCredFile: ${{ parameters.azureMsiCredFile }}
          backendResourceGroupName: ${{ parameters.backendResourceGroupName }}
          backendStorageAccountName: ${{ parameters.backendStorageAccountName }}
          backendContainerName: ${{ parameters.backendContainerName }}
          tfStateName: '${{ parameters.stage }}.tfstate'
          workingDirectory: ${{ parameters.workingDirectory }}

      - script: |
          envsubst < "../env_vars/${{ parameters.stage }}.tfvars" > "terraform.tfvars"
        displayName: Prepare Terraform variables
        workingDirectory: ${{ parameters.workingDirectory }}

      - template: ../steps/terraform-apply.yml
        parameters:
          applyDeployment: ${{ parameters.applyDeployment }}
          azureMsiCredFile: ${{ parameters.azureMsiCredFile }}
          tfplanName: $(tfplanName)
          workingDirectory: ${{ parameters.workingDirectory }}