parameters:
  - name: applyDeployment
  - name: azureMsiCredFile
  - name: backendContainerName
  - name: backendResourceGroupName
  - name: backendStorageAccountName
  - name: releaseId
  - name: resourceLocation
  - name: stage
  - name: workingDirectory

jobs:
  - job: provisionEnvironment
    displayName: "Provision environment"

    variables:
      - name: tfplanName
        value: tfplan-${{ parameters.releaseId }}.tfplan
    
    steps:
      - template: ../steps/terraform-setup.yml
        parameters:
          azureMsiCredFile: ${{ parameters.azureMsiCredFile }}
          backendResourceGroupName: ${{ parameters.backendResourceGroupName }}
          backendStorageAccountName: ${{ parameters.backendStorageAccountName }}
          backendContainerName: ${{ parameters.backendContainerName }}
          stage: ${{ parameters.stage }}
          workingDirectory: ${{ parameters.workingDirectory }}

      - template: ../steps/terraform-apply.yml
        parameters:
          applyDeployment: ${{ parameters.applyDeployment }}
          resourceLocation: resourceLocation
          stage: ${{ parameters.stage }}
          tfplanName: $(tfplanName)
          workingDirectory: ${{ parameters.workingDirectory }}