parameters:
  - name: applyDeployment
  - name: environmentName
  - name: location
  - name: tfplanName
  - name: workingDirectory

steps:
  - script: |
      terraform plan -input=false -out ${{ parameters.tfplanName }}
    displayName: Terraform plan
    workingDirectory: ${{ parameters.workingDirectory }}
    env:
      "TF_VAR_environment_name": '${{ parameters.environmentName }}'
      "TF_VAR_location": '${{ parameters.location }}'
    
  - script: |
      terraform apply ${{ parameters.tfplanName }}
    displayName: Terraform apply
    workingDirectory: ${{ parameters.workingDirectory }}
    condition: and(succeeded(), ${{ parameters.applyDeployment }})