trigger:
  none

variables:
  - group: Backend-Resource-Names
  - name: workingDirectory
    value: 
  - name: tfplanName
    value: destroy.tfplan
  - name: isMainBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

stages:
  - template : templates/stages/api-destroy.yml
    parameters:
      stage: dev
      applyDeployment: True
      azureMsiCredFile: arm.credentials.dev.auto.tfvars
      backendContainerName: $(BackendContainerName)
      backendResourceGroupName: $(BackendResourceGroupName)
      backendStorageAccountName: $(BackendStorageAccountName)
      workingDirectory: $(System.DefaultWorkingDirectory)/deploy/terraform/provision
      
  - template : templates/stages/api-destroy.yml
    parameters:
      stage: qa
      applyDeployment: True
      azureMsiCredFile: arm.credentials.dev.auto.tfvars
      backendContainerName: $(BackendContainerName)
      backendResourceGroupName: $(BackendResourceGroupName)
      backendStorageAccountName: $(BackendStorageAccountName)
      workingDirectory: $(System.DefaultWorkingDirectory)/deploy/terraform/provision