trigger:
  none

variables:
  - group: Backend-Resource-Names
  - name: workingDirectory
    value: 
  - name: tfplanName
    value: destroy.tfplan
  - name: isMainBranch
    value: ${{ eq(variables['Build.SourceBranch'], 'refs/heads/main') }}

stages:
  - template : templates/stages/api-destroy.yml
    parameters:
      stage: dev
      applyDeployment: True
      azureMsiCredFile: arm.credentials.dev.auto.tfvars
      backendContainerName: ${{ parameters.backendContainerName }}
      backendResourceGroupName: ${{ parameters.backendResourceGroupName }}
      backendStorageAccountName: ${{ parameters.backendStorageAccountName }}
      workingDirectory: $(System.DefaultWorkingDirectory)/deploy/terraform/provision

  - template : templates/stages/api-destroy.yml
    parameters:
      stage: qa
      applyDeployment: ${{ variables.isMainBranch }}
      azureMsiCredFile: arm.credentials.dev.auto.tfvars
      backendContainerName: ${{ parameters.backendContainerName }}
      backendResourceGroupName: ${{ parameters.backendResourceGroupName }}
      backendStorageAccountName: ${{ parameters.backendStorageAccountName }}
      workingDirectory: $(System.DefaultWorkingDirectory)/deploy/terraform/provision

